import { chromium } from 'playwright';
import fs from 'fs';
const U = process.argv[2] || 'http://localhost:4173/jm-finance/'; const OUT = process.argv[3] || 'screenshots/v14';
const SHOT = (process.argv[4] || '360x740,390x844,1366x768').split(',');
fs.mkdirSync(OUT, { recursive: true });
const VPS = [[375,667],[390,844],[360,740],[412,915],[430,932],[820,1180,'tablet'],[1366,768,'desktop']];
const fails = [], errs = []; let n0 = 0; const ok = (c, m) => { n0++; if (!c) fails.push(m); };
const b = await chromium.launch();
for (const [w, h, kind] of VPS) for (const scheme of ['light', 'dark']) {
  const n = `${w}x${h}`, tag = scheme === 'light' ? 'claro' : 'escuro', shots = SHOT.includes(n);
  const ctx = await b.newContext({ viewport: { width: w, height: h }, deviceScaleFactor: kind === 'desktop' ? 1 : 2, locale: 'pt-BR', timezoneId: 'America/Sao_Paulo', isMobile: !kind, hasTouch: kind !== 'desktop', colorScheme: scheme });
  const p = await ctx.newPage(); p.on('pageerror', e => errs.push(`${n}/${scheme}: ${e.message}`)); p.on('console', m => m.type() === 'error' && errs.push(`${n}/${scheme}: ${m.text()}`));
  const wait = ms => p.waitForTimeout(ms);
  const shot = async nm => { if (shots) { await wait(500); await p.screenshot({ path: `${OUT}/${tag}-${n}-${nm}.png` }); } };
  const th = () => p.evaluate(() => [document.documentElement.dataset.theme, localStorage.getItem('jm:theme'), localStorage.getItem('jm:themePicked')]);
  const fits = sel => p.evaluate(s => { const e = document.querySelector(s); if (!e) return 'ausente'; const r = e.getBoundingClientRect(); return r.left >= -0.5 && r.right <= innerWidth + 0.5 && r.top >= -0.5 && r.bottom <= innerHeight + 0.5 ? true : `${Math.round(r.left)},${Math.round(r.top)},${Math.round(r.right)},${Math.round(r.bottom)}`; }, sel);
  await p.goto(U + '?nosplash'); await p.evaluate(() => { localStorage.clear(); sessionStorage.setItem('jm:nm', '1'); }); await p.reload(); await wait(700);
  await p.click('.welcome .accept'); await p.locator('.welcome .btn').last().click(); await wait(900);
  ok(await p.locator('.tp-panel').isVisible(), `${n}/${scheme} picker não apareceu`);
  ok((await th())[0] === scheme, `${n}/${scheme} picker não começou no tema do aparelho`);
  ok(await fits('.tp-go') === true, `${n}/${scheme} Continuar fora da tela: ${await fits('.tp-go')}`);
  const ov = await p.evaluate(() => document.documentElement.scrollWidth - innerWidth); ok(ov <= 1, `${n}/${scheme} overflow ${ov}`);
  await shot('01-escolha-tema');
  const other = scheme === 'light' ? 'dark' : 'light';
  await p.click(`.tp-opt:has-text("${other === 'light' ? 'Claro' : 'Escuro'}")`); await wait(500);
  let t = await th(); ok(t[0] === other && t[1] === other, `${n}/${scheme} prévia não aplicou: ${t}`);
  await shot('02-escolha-outro');
  await p.click(`.tp-opt:has-text("${scheme === 'light' ? 'Claro' : 'Escuro'}")`); await wait(400);
  ok((await th())[0] === scheme, `${n}/${scheme} não voltou`);
  await p.click('.tp-go'); await wait(900);
  ok(!(await p.locator('.tp-panel').count()), `${n}/${scheme} picker não fechou`);
  ok(await p.locator('.tip-box').isVisible(), `${n}/${scheme} dica não apareceu`);
  ok(await fits('.tip-box') === true, `${n}/${scheme} dica fora da tela: ${await fits('.tip-box')}`);
  const aim = await p.evaluate(() => { const a = document.querySelector('.tip-arrow').getBoundingClientRect(), b = document.querySelector('.theme-btn').getBoundingClientRect(); return Math.abs((a.left + a.width / 2) - (b.left + b.width / 2)) < 3 && a.top >= b.bottom; });
  ok(aim, `${n}/${scheme} seta não aponta para o botão`);
  await shot('03-dica-sol-lua');
  await p.click('.tip-box'); await wait(600);
  ok(!(await p.locator('.tip-wrap').count()), `${n}/${scheme} dica não fechou`);
  t = await th(); ok(t[2] === '1' && t[1] === scheme, `${n}/${scheme} escolha não salva: ${t}`);
  await p.reload(); await wait(900);
  ok(!(await p.locator('.tp-panel, .tip-wrap').count()), `${n}/${scheme} reapareceu após recarregar`);
  // usuário antigo (termos já aceitos): nunca vê
  await p.evaluate(() => localStorage.removeItem('jm:themePicked')); await p.reload(); await wait(900);
  ok(!(await p.locator('.tp-panel, .tip-wrap').count()), `${n}/${scheme} usuário antigo viu a escolha`);
  await shot('04-app-depois');
  console.log(n, scheme, 'ok'); await ctx.close();
}
await b.close();
console.log(`checagens: ${n0} | falhas: ${fails.length ? '\n' + fails.join('\n') : 'nenhuma'}\nerros: ${errs.length ? errs.join('\n') : 'nenhum'}`);
